server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: city-service
          uri: http://localhost:8081
          predicates:
            - Path=/city/**, /city-info/** 
        - id: route-service
          uri: http://localhost:8082
          predicates:
            - Path=/route/**, /routes/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
