services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python_monolith:
    build: ../Python/MonolithicApp
    container_name: python_monolith
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      PYTHONPATH: /code
    ports:
      - '8000:8000'
    volumes:
      - ../Python/MonolithicApp:/code/MonolithicApp
      - ../Python/src:/code/src

  python_city_service:
    build: ../Python/MicroserviceApp/CityService
    container_name: python_city_service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      PYTHONPATH: /code
    ports:
      - '8001:8001'
    volumes:
      - ../Python/MicroserviceApp/CityService:/code/MicroserviceApp/CityService
      - ../Python/src:/code/src

  python_route_service:
    build: ../Python/MicroserviceApp/RouteService
    container_name: python_route_service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      PYTHONPATH: /code
    ports:
      - '8002:8002'
    volumes:
      - ../Python/MicroserviceApp/RouteService:/code/MicroserviceApp/RouteService
      - ../Python/src:/code/src

  java_monolith:
    build: ../Java/MonolithicApp
    container_name: java_monolith
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - '8003:8003'

  java_city_service:
    build:
      context: ../Java/MicroserviceApp
      dockerfile: city-service/Dockerfile
    container_name: java_city_service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - '8004:8004'

  java_route_service:
    build:
      context: ../Java/MicroserviceApp
      dockerfile: route-service/Dockerfile
    container_name: java_route_service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - '8005:8005'

  dotnet_monolith:
    build: ../NET/MonolithicApp
    container_name: dotnet_monolith
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Postgres: 'Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword'
    ports:
      - '8006:8080'

  dotnet_city_service:
    build: ../NET/MicroserviceApp/CityService
    container_name: dotnet_city_service
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Postgres: 'Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword'
    ports:
      - '8007:8080'

  dotnet_route_service:
    build: ../NET/MicroserviceApp/RouteService
    container_name: dotnet_route_service
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Postgres: 'Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword'
    ports:
      - '8008:8080'

volumes:
  pgdata:
